// tslint:disable no-magic-numbers

import { Duration, Location, musicalAs, Tone } from '@musical-patterns/utilities'

const HOUNDSTOOTHTOPIA_THEME_INITIAL_HZ_PHYSICALIZATION: Tone = musicalAs.Tone(141.42)
const HOUNDSTOOTHTOPIA_THEME_INITIAL_MS_PHYSICALIZATION: Duration = musicalAs.Duration(471.4)
const HOUNDSTOOTHTOPIA_THEME_INITIAL_METERS_PHYSICALIZATION: Location = musicalAs.Location(4)

export {
    HOUNDSTOOTHTOPIA_THEME_INITIAL_MS_PHYSICALIZATION,
    HOUNDSTOOTHTOPIA_THEME_INITIAL_HZ_PHYSICALIZATION,
    HOUNDSTOOTHTOPIA_THEME_INITIAL_METERS_PHYSICALIZATION,
}
