// tslint:disable no-magic-numbers

import { as, Hz, Meters, Ms, Scalar } from '@musical-patterns/utilities'

const HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_FREQUENCY: Scalar<Hz> = as.Scalar<Hz>(141.42)
const HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_DURATION: Scalar<Ms> = as.Scalar<Ms>(471.4)
const HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_POSITION_SCALAR: Scalar<Meters> = as.Scalar<Meters>(4)

export {
    HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_DURATION,
    HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_FREQUENCY,
    HOUNDSTOOTHTOPIA_THEME_INITIAL_BASE_POSITION_SCALAR,
}
